<?php 
/* 	
If you see this text in your browser, PHP is not configured correctly on this hosting provider. 
Contact your hosting provider regarding PHP configuration for your site.

PHP file generated by Adobe Muse CC 2017.0.0.363
*/

require_once('form_process.php');

$form = array(
	'subject' => 'WidgetsLibrary::simple_contact Form 提交',
	'heading' => '新表单提交',
	'success_redirect' => '',
	'resources' => array(
		'checkbox_checked' => '已选中',
		'checkbox_unchecked' => '未选中',
		'submitted_from' => '表单提交自网站：%s',
		'submitted_by' => '访客 IP 地址：%s',
		'too_many_submissions' => '来自此 IP 的提交次数太频繁',
		'failed_to_send_email' => '发送电子邮件失败',
		'invalid_reCAPTCHA_private_key' => '无效 reCAPTCHA 私钥。',
		'invalid_reCAPTCHA2_private_key' => 'Invalid reCAPTCHA 2.0 private key.',
		'invalid_reCAPTCHA2_server_response' => 'Invalid reCAPTCHA 2.0 server response.',
		'invalid_field_type' => '未知字段类型 \'%s\'。',
		'invalid_form_config' => '字段 \'%s\' 具有无效配置。',
		'unknown_method' => '位置服务器请求方法'
	),
	'email' => array(
		'from' => 'cherrycaowen@gmail.com',
		'to' => 'cherrycaowen@gmail.com'
	),
	'fields' => array(
		'custom_U6127' => array(
			'order' => 1,
			'type' => 'string',
			'label' => 'Custom:',
			'required' => true,
			'errors' => array(
				'required' => '字段 \'Custom:\' 为必填项。'
			)
		),
		'Email' => array(
			'order' => 2,
			'type' => 'email',
			'label' => 'Custom:',
			'required' => true,
			'errors' => array(
				'required' => '字段 \'Custom:\' 为必填项。',
				'format' => '字段 \'Custom:\' 含有无效电子邮件地址。'
			)
		),
		'custom_U6121' => array(
			'order' => 3,
			'type' => 'string',
			'label' => 'Custom:',
			'required' => false,
			'errors' => array(
			)
		)
	)
);

process_form($form);
?>
